# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ar1_sim <- function(rho, innovs) {
    .Call(`_RWSIM_ar1_sim`, rho, innovs)
}

seq_cpp <- function(lo, hi) {
    .Call(`_RWSIM_seq_cpp`, lo, hi)
}

t_col_sum <- function(dat, t) {
    .Call(`_RWSIM_t_col_sum`, dat, t)
}

detrend_recursive <- function(dat) {
    .Call(`_RWSIM_detrend_recursive`, dat)
}

mlag <- function(dat, p, drop) {
    .Call(`_RWSIM_mlag`, dat, p, drop)
}

mdiff <- function(dat, p, drop) {
    .Call(`_RWSIM_mdiff`, dat, p, drop)
}

DF_Reg_Mat <- function(y, p, model = "nc", omit_y_lag = FALSE, trim = 0L) {
    .Call(`_RWSIM_DF_Reg_Mat`, y, p, model, omit_y_lag, trim)
}

Detrend <- function(Y, model = "c") {
    .Call(`_RWSIM_Detrend`, Y, model)
}

FD_Detrend <- function(Y, model = "c") {
    .Call(`_RWSIM_FD_Detrend`, Y, model)
}

GLS_Detrend <- function(dat, model) {
    .Call(`_RWSIM_GLS_Detrend`, dat, model)
}

DF_Reg_field <- function(Y, p, model, remove_lags = 0L, trim = 0L) {
    .Call(`_RWSIM_DF_Reg_field`, Y, p, model, remove_lags, trim)
}

S2_AR <- function(dat, k, model, remove_lags) {
    .Call(`_RWSIM_S2_AR`, dat, k, model, remove_lags)
}

DF_Reg <- function(Y, p, model, remove_lags, trim = 0L) {
    .Call(`_RWSIM_DF_Reg`, Y, p, model, remove_lags, trim)
}

ERS <- function(dat, p, model, remove_lags, trim = 0L) {
    .Call(`_RWSIM_ERS`, dat, p, model, remove_lags, trim)
}

OLSRes <- function(y, X) {
    .Call(`_RWSIM_OLSRes`, y, X)
}

ARMA_sim <- function(ar_coefs, ma_coefs, innovs, cumsum = FALSE, rho = 1, mu = 0, delta = 0) {
    .Call(`_RWSIM_ARMA_sim`, ar_coefs, ma_coefs, innovs, cumsum, rho, mu, delta)
}

IC <- function(Y, p, pmax, model, remove_lags, penalty = "BIC", modified = FALSE) {
    .Call(`_RWSIM_IC`, Y, p, pmax, model, remove_lags, penalty, modified)
}

Mtests <- function(dat, p, model, remove_lags) {
    .Call(`_RWSIM_Mtests`, dat, p, model, remove_lags)
}

DF_Pred_regressors <- function(y, p, model = "nc") {
    .Call(`_RWSIM_DF_Pred_regressors`, y, p, model)
}

forecast_ADF <- function(y, coefs, pmax, model, h, differences = TRUE) {
    .Call(`_RWSIM_forecast_ADF`, y, coefs, pmax, model, h, differences)
}

Jstat <- function(series_scaled, R, alpha, J_sigma, model) {
    .Call(`_RWSIM_Jstat`, series_scaled, R, alpha, J_sigma, model)
}

