# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seq_cpp <- function(lo, hi) {
    .Call(`_RWSIM_seq_cpp`, lo, hi)
}

mlag <- function(dat, p, drop) {
    .Call(`_RWSIM_mlag`, dat, p, drop)
}

mdiff <- function(dat, p, drop) {
    .Call(`_RWSIM_mdiff`, dat, p, drop)
}

DF_Reg_Mat <- function(y, p, model = "nc", omit_y_lag = FALSE) {
    .Call(`_RWSIM_DF_Reg_Mat`, y, p, model, omit_y_lag)
}

DF_Reg_field <- function(Y, p, model, remove_lags) {
    .Call(`_RWSIM_DF_Reg_field`, Y, p, model, remove_lags)
}

S2_AR <- function(dat, k, model, remove_lags) {
    .Call(`_RWSIM_S2_AR`, dat, k, model, remove_lags)
}

DF_Reg <- function(Y, p, model, remove_lags) {
    .Call(`_RWSIM_DF_Reg`, Y, p, model, remove_lags)
}

OLSRes <- function(y, X) {
    .Call(`_RWSIM_OLSRes`, y, X)
}

ARMA_sim <- function(ar_coefs, ma_coefs, innovs) {
    .Call(`_RWSIM_ARMA_sim`, ar_coefs, ma_coefs, innovs)
}

