// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ar1_sim
arma::mat ar1_sim(const double& rho, const arma::vec& innovs);
RcppExport SEXP _RWSIM_ar1_sim(SEXP rhoSEXP, SEXP innovsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type innovs(innovsSEXP);
    rcpp_result_gen = Rcpp::wrap(ar1_sim(rho, innovs));
    return rcpp_result_gen;
END_RCPP
}
// seq_cpp
arma::vec seq_cpp(const int& lo, const int& hi);
RcppExport SEXP _RWSIM_seq_cpp(SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type lo(loSEXP);
    Rcpp::traits::input_parameter< const int& >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_cpp(lo, hi));
    return rcpp_result_gen;
END_RCPP
}
// t_col_sum
arma::vec t_col_sum(const arma::mat& dat, const int& t);
RcppExport SEXP _RWSIM_t_col_sum(SEXP datSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int& >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(t_col_sum(dat, t));
    return rcpp_result_gen;
END_RCPP
}
// detrend_recursive
arma::mat detrend_recursive(const arma::mat& dat);
RcppExport SEXP _RWSIM_detrend_recursive(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(detrend_recursive(dat));
    return rcpp_result_gen;
END_RCPP
}
// mlag
arma::mat mlag(const arma::mat& dat, const int& p, const bool& drop);
RcppExport SEXP _RWSIM_mlag(SEXP datSEXP, SEXP pSEXP, SEXP dropSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const bool& >::type drop(dropSEXP);
    rcpp_result_gen = Rcpp::wrap(mlag(dat, p, drop));
    return rcpp_result_gen;
END_RCPP
}
// mdiff
arma::mat mdiff(const arma::mat& dat, const int& p, const bool& drop);
RcppExport SEXP _RWSIM_mdiff(SEXP datSEXP, SEXP pSEXP, SEXP dropSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const bool& >::type drop(dropSEXP);
    rcpp_result_gen = Rcpp::wrap(mdiff(dat, p, drop));
    return rcpp_result_gen;
END_RCPP
}
// DF_Reg_Mat
arma::mat DF_Reg_Mat(const arma::mat& y, const int& p, const std::string& model, const bool& omit_y_lag, const int& trim);
RcppExport SEXP _RWSIM_DF_Reg_Mat(SEXP ySEXP, SEXP pSEXP, SEXP modelSEXP, SEXP omit_y_lagSEXP, SEXP trimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type omit_y_lag(omit_y_lagSEXP);
    Rcpp::traits::input_parameter< const int& >::type trim(trimSEXP);
    rcpp_result_gen = Rcpp::wrap(DF_Reg_Mat(y, p, model, omit_y_lag, trim));
    return rcpp_result_gen;
END_RCPP
}
// Detrend
arma::mat Detrend(const arma::mat& Y, const std::string& model);
RcppExport SEXP _RWSIM_Detrend(SEXP YSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(Detrend(Y, model));
    return rcpp_result_gen;
END_RCPP
}
// FD_Detrend
arma::mat FD_Detrend(const arma::mat& Y, const std::string& model);
RcppExport SEXP _RWSIM_FD_Detrend(SEXP YSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(FD_Detrend(Y, model));
    return rcpp_result_gen;
END_RCPP
}
// GLS_Detrend
arma::mat GLS_Detrend(arma::mat dat, std::string model);
RcppExport SEXP _RWSIM_GLS_Detrend(SEXP datSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type dat(datSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(GLS_Detrend(dat, model));
    return rcpp_result_gen;
END_RCPP
}
// DF_Reg_field
arma::field<arma::mat> DF_Reg_field(const arma::mat& Y, const int& p, const std::string& model, const arma::uvec& remove_lags, const int& trim);
RcppExport SEXP _RWSIM_DF_Reg_field(SEXP YSEXP, SEXP pSEXP, SEXP modelSEXP, SEXP remove_lagsSEXP, SEXP trimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type remove_lags(remove_lagsSEXP);
    Rcpp::traits::input_parameter< const int& >::type trim(trimSEXP);
    rcpp_result_gen = Rcpp::wrap(DF_Reg_field(Y, p, model, remove_lags, trim));
    return rcpp_result_gen;
END_RCPP
}
// S2_AR
double S2_AR(const arma::mat& dat, const int& k, const std::string& model, const arma::uvec& remove_lags);
RcppExport SEXP _RWSIM_S2_AR(SEXP datSEXP, SEXP kSEXP, SEXP modelSEXP, SEXP remove_lagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type remove_lags(remove_lagsSEXP);
    rcpp_result_gen = Rcpp::wrap(S2_AR(dat, k, model, remove_lags));
    return rcpp_result_gen;
END_RCPP
}
// DF_Reg
double DF_Reg(const arma::mat& Y, const int& p, const std::string& model, const arma::uvec& remove_lags, const int& trim);
RcppExport SEXP _RWSIM_DF_Reg(SEXP YSEXP, SEXP pSEXP, SEXP modelSEXP, SEXP remove_lagsSEXP, SEXP trimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type remove_lags(remove_lagsSEXP);
    Rcpp::traits::input_parameter< const int& >::type trim(trimSEXP);
    rcpp_result_gen = Rcpp::wrap(DF_Reg(Y, p, model, remove_lags, trim));
    return rcpp_result_gen;
END_RCPP
}
// ERS
double ERS(const arma::mat& dat, const int& p, const std::string& model, const arma::uvec& remove_lags, const int& trim);
RcppExport SEXP _RWSIM_ERS(SEXP datSEXP, SEXP pSEXP, SEXP modelSEXP, SEXP remove_lagsSEXP, SEXP trimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type remove_lags(remove_lagsSEXP);
    Rcpp::traits::input_parameter< const int& >::type trim(trimSEXP);
    rcpp_result_gen = Rcpp::wrap(ERS(dat, p, model, remove_lags, trim));
    return rcpp_result_gen;
END_RCPP
}
// OLSRes
arma::field<arma::mat> OLSRes(const arma::vec& y, const arma::mat& X);
RcppExport SEXP _RWSIM_OLSRes(SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(OLSRes(y, X));
    return rcpp_result_gen;
END_RCPP
}
// ARMA_sim
arma::mat ARMA_sim(arma::vec ar_coefs, arma::vec ma_coefs, const arma::vec& innovs, const bool& cumsum, const double& rho, const double& mu, const double& delta);
RcppExport SEXP _RWSIM_ARMA_sim(SEXP ar_coefsSEXP, SEXP ma_coefsSEXP, SEXP innovsSEXP, SEXP cumsumSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ar_coefs(ar_coefsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ma_coefs(ma_coefsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type innovs(innovsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type cumsum(cumsumSEXP);
    Rcpp::traits::input_parameter< const double& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(ARMA_sim(ar_coefs, ma_coefs, innovs, cumsum, rho, mu, delta));
    return rcpp_result_gen;
END_RCPP
}
// IC
double IC(const arma::mat& Y, const int& p, const int& pmax, const std::string& model, const arma::uvec& remove_lags, const std::string& penalty, const bool& modified);
RcppExport SEXP _RWSIM_IC(SEXP YSEXP, SEXP pSEXP, SEXP pmaxSEXP, SEXP modelSEXP, SEXP remove_lagsSEXP, SEXP penaltySEXP, SEXP modifiedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int& >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type remove_lags(remove_lagsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< const bool& >::type modified(modifiedSEXP);
    rcpp_result_gen = Rcpp::wrap(IC(Y, p, pmax, model, remove_lags, penalty, modified));
    return rcpp_result_gen;
END_RCPP
}
// Mtests
arma::mat Mtests(const arma::mat dat, const int p, const std::string model, const arma::uvec& remove_lags);
RcppExport SEXP _RWSIM_Mtests(SEXP datSEXP, SEXP pSEXP, SEXP modelSEXP, SEXP remove_lagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type remove_lags(remove_lagsSEXP);
    rcpp_result_gen = Rcpp::wrap(Mtests(dat, p, model, remove_lags));
    return rcpp_result_gen;
END_RCPP
}
// DF_Pred_regressors
arma::mat DF_Pred_regressors(const arma::mat& y, const int& p, const std::string& model);
RcppExport SEXP _RWSIM_DF_Pred_regressors(SEXP ySEXP, SEXP pSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(DF_Pred_regressors(y, p, model));
    return rcpp_result_gen;
END_RCPP
}
// forecast_ADF
arma::mat forecast_ADF(const arma::rowvec& y, const arma::colvec& coefs, const int& pmax, const std::string& model, const int& h, const bool& differences);
RcppExport SEXP _RWSIM_forecast_ADF(SEXP ySEXP, SEXP coefsSEXP, SEXP pmaxSEXP, SEXP modelSEXP, SEXP hSEXP, SEXP differencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< const int& >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const int& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const bool& >::type differences(differencesSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_ADF(y, coefs, pmax, model, h, differences));
    return rcpp_result_gen;
END_RCPP
}
// Jstat
double Jstat(arma::vec series_scaled, int R, double alpha, double J_sigma, std::string model);
RcppExport SEXP _RWSIM_Jstat(SEXP series_scaledSEXP, SEXP RSEXP, SEXP alphaSEXP, SEXP J_sigmaSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type series_scaled(series_scaledSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type J_sigma(J_sigmaSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(Jstat(series_scaled, R, alpha, J_sigma, model));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RWSIM_ar1_sim", (DL_FUNC) &_RWSIM_ar1_sim, 2},
    {"_RWSIM_seq_cpp", (DL_FUNC) &_RWSIM_seq_cpp, 2},
    {"_RWSIM_t_col_sum", (DL_FUNC) &_RWSIM_t_col_sum, 2},
    {"_RWSIM_detrend_recursive", (DL_FUNC) &_RWSIM_detrend_recursive, 1},
    {"_RWSIM_mlag", (DL_FUNC) &_RWSIM_mlag, 3},
    {"_RWSIM_mdiff", (DL_FUNC) &_RWSIM_mdiff, 3},
    {"_RWSIM_DF_Reg_Mat", (DL_FUNC) &_RWSIM_DF_Reg_Mat, 5},
    {"_RWSIM_Detrend", (DL_FUNC) &_RWSIM_Detrend, 2},
    {"_RWSIM_FD_Detrend", (DL_FUNC) &_RWSIM_FD_Detrend, 2},
    {"_RWSIM_GLS_Detrend", (DL_FUNC) &_RWSIM_GLS_Detrend, 2},
    {"_RWSIM_DF_Reg_field", (DL_FUNC) &_RWSIM_DF_Reg_field, 5},
    {"_RWSIM_S2_AR", (DL_FUNC) &_RWSIM_S2_AR, 4},
    {"_RWSIM_DF_Reg", (DL_FUNC) &_RWSIM_DF_Reg, 5},
    {"_RWSIM_ERS", (DL_FUNC) &_RWSIM_ERS, 5},
    {"_RWSIM_OLSRes", (DL_FUNC) &_RWSIM_OLSRes, 2},
    {"_RWSIM_ARMA_sim", (DL_FUNC) &_RWSIM_ARMA_sim, 7},
    {"_RWSIM_IC", (DL_FUNC) &_RWSIM_IC, 7},
    {"_RWSIM_Mtests", (DL_FUNC) &_RWSIM_Mtests, 4},
    {"_RWSIM_DF_Pred_regressors", (DL_FUNC) &_RWSIM_DF_Pred_regressors, 3},
    {"_RWSIM_forecast_ADF", (DL_FUNC) &_RWSIM_forecast_ADF, 6},
    {"_RWSIM_Jstat", (DL_FUNC) &_RWSIM_Jstat, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_RWSIM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
